## Deliverable 2. Create a Customer Travel Destinations Map.

In [22]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [23]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database.csv")

In [24]:
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Araguacu,BR,-12.9306,-49.8264,82.26,72,100,5.73,overcast clouds,2021-11-06 17:34:24
1,1,Klaksvik,FO,62.2266,-6.5890,49.12,98,100,19.62,overcast clouds,2021-11-06 17:34:25
2,2,Nabire,ID,-3.3667,135.4833,75.88,90,100,1.77,overcast clouds,2021-11-06 17:34:26
3,3,Ust-Nera,RU,64.5667,143.2000,-16.85,94,27,5.08,scattered clouds,2021-11-06 17:34:26
4,4,Visby,SE,57.6409,18.2960,49.86,81,20,9.22,few clouds,2021-11-06 17:34:27

In [25]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
locations = city_data_df[["Lat", "Lng"]]
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

In [26]:
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [28]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [29]:
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Araguacu,BR,-12.9306,-49.8264,82.26,72,100,5.73,overcast clouds,2021-11-06 17:34:24
2,2,Nabire,ID,-3.3667,135.4833,75.88,90,100,1.77,overcast clouds,2021-11-06 17:34:26
6,6,Vilhena,BR,-12.7406,-60.1458,77.22,78,75,11.50,broken clouds,2021-11-06 17:34:28
8,8,Kapaa,US,22.0752,-159.3190,75.52,81,20,13.80,few clouds,2021-11-06 17:34:29
13,13,Rikitea,PF,-23.1203,-134.9692,75.27,82,100,16.22,overcast clouds,2021-11-06 17:34:31
19,19,San Policarpo,PH,12.1791,125.5072,81.57,84,100,13.80,overcast clouds,2021-11-06 17:34:34
22,22,Georgetown,MY,5.4112,100.3354,80.53,92,40,5.01,light rain,2021-11-06 17:34:35
25,25,Musiri,IN,10.9333,78.4500,82.44,94,100,5.91,overcast clouds,2021-11-06 17:34:36
27,27,Atuona,PF,-9.8000,-139.0333,77.95,77,36,18.34,light rain,2021-11-06 17:34:37
29,29,Santa Rosa Del Sur,CO,7.9644,-74.0544,81.09,68,89,0.87,overcast clouds,2021-11-06 17:34:38

In [30]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.notnull().sum()
preferred_cities_df.count()
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                1
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
Date                   0
dtype: int64

In [31]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Araguacu,BR,-12.9306,-49.8264,82.26,72,100,5.73,overcast clouds,2021-11-06 17:34:24
2,2,Nabire,ID,-3.3667,135.4833,75.88,90,100,1.77,overcast clouds,2021-11-06 17:34:26
6,6,Vilhena,BR,-12.7406,-60.1458,77.22,78,75,11.50,broken clouds,2021-11-06 17:34:28
8,8,Kapaa,US,22.0752,-159.3190,75.52,81,20,13.80,few clouds,2021-11-06 17:34:29
13,13,Rikitea,PF,-23.1203,-134.9692,75.27,82,100,16.22,overcast clouds,2021-11-06 17:34:31
...,...,...,...,...,...,...,...,...,...,...,...
694,694,Pedernales,DO,18.0384,-71.7440,85.71,61,16,2.66,few clouds,2021-11-06 17:39:23
702,702,Auki,SB,-8.7676,160.7034,77.27,81,27,4.29,scattered clouds,2021-11-06 17:39:27
704,704,Balabac,PH,7.9868,117.0645,81.23,83,84,7.99,broken clouds,2021-11-06 17:39:28
705,705,Pandharpur,IN,17.6667,75.3333,76.73,47,70,10.49,broken clouds,2021-11-06 17:39:28
711,711,Manyana,BW,-23.4000,21.7167,87.26,12,54,6.13,broken clouds,2021-11-06 17:39:30

In [32]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Araguacu,BR,82.26,overcast clouds,-12.9306,-49.8264,
2,Nabire,ID,75.88,overcast clouds,-3.3667,135.4833,
6,Vilhena,BR,77.22,broken clouds,-12.7406,-60.1458,
8,Kapaa,US,75.52,few clouds,22.0752,-159.3190,
13,Rikitea,PF,75.27,overcast clouds,-23.1203,-134.9692,
19,San Policarpo,PH,81.57,overcast clouds,12.1791,125.5072,
22,Georgetown,MY,80.53,light rain,5.4112,100.3354,
25,Musiri,IN,82.44,overcast clouds,10.9333,78.4500,
27,Atuona,PF,77.95,light rain,-9.8000,-139.0333,
29,Santa Rosa Del Sur,CO,81.09,overcast clouds,7.9644,-74.0544,

In [33]:

len(hotel_df)

237

In [ ]:

# 6a. Set parameters to search for hotels with 5000 meters.
# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params = {
        "location": f"{lat},{lng}",
        "radius": 5000,
        "types" : "hotel",
        "key": g_key
    }


    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
        
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError): print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.

In [ ]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.head()

In [ ]:
# 8a. Create the output File (CSV)
# Create the output file (CSV).
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [ ]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig